### ISSUE TITLE
Mirror optic for User Display

### ISSUE THREAD

**Issue by Sebener** [neue-welt/teleprompter#14]
Needs to change the Screen for the Teleprompter Mirror on the Raspberry

**Comment by tobinski** [comment]
One option is to flip the screen directly on the [raspi](https://www.raspberrypi.org/documentation/configuration/config-txt/video.md) The `lcd_rotate` and `display_hdmi_rotate` may be an option

**Comment by tobinski** [comment]
can we close this. Can you provide some insights how you did it?
